topic: "Как научить кота программировать на Python"

output_file: post_content.txt

model:
  name: mixtral-8x7b-32768
  temperature: 0.2
  max_tokens: 900

# models: https://console.groq.com/docs/models
